# Generated by Django 3.2.18 on 2026-04-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyquestion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='surveyquestionitem',
            unique_together=set(),
        ),
    ]
