# Generated by Django 3.2.18 on 2026-04-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260417_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_question_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.surveyquestionitem', verbose_name='Опрос'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('user', 'survey_question', 'survey_question_item')},
        ),
    ]
